# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: listallorgs
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
          sudo curl -L --include --header "Content-Type: application/json; charset=utf-8" --header "Authorization: token da12766a-46b6-4186-8ba1-83eb1aae653c" 'https://snyk.io/api/v1/orgs'
          git remote -v
          sudo curl -H "Accept: application/vnd.github.v3+json" -u roberthicksiii@gmail.com:$GH_TOKEN https://api.github.com/organizations
          
          
    - name: gitparse
    
      uses: theowenyoung/git-url-parse@v1
      with:
       url: https://github.com/rhicksiii91/java-goof
     

